resources:
  - icon: github
    name: technical-test-git
    source:
      uri: https://github.com/jacob-302/technical-test.git
      branch: concourse
    type: git
  - icon: docker
    name: technical-test-docker
    type: docker-image
    source:
      repository: ((docker-creds.username))/technical-test
      username: ((docker-creds.username))
      password: ((docker-creds.password))

jobs:
- name: test-and-build
  serial: true
  plan:
  - get: technical-test-git
    trigger: true
  - config:
      caches:
      - path: $HOME/.m2/repository
      - path: $HOME/.gradle/caches
      - path: $HOME/.gradle/wrapper
      image_resource:
        source:
          repository: gradle
          tag: 8.10-jdk21
        type: registry-image
      inputs:
        - name: technical-test-git
      outputs:
        - name: jar
          path: technical-test-git/api/build/libs
      platform: linux
      run:
        args:
          - -c
          - |
            cd technical-test-git/api
            ./gradlew assemble test sonarqube --no-daemon
        path: /bin/sh
        user: root
    task: run-tests
  - put: technical-test-docker
    params:
      tag_as_latest: true
      build: technical-test-git/api
      build_args:
        git_sha: "$(cat technical-test-git/.git/refs/heads/main)"
      tag_file: technical-test-git/.git/refs/heads/main
  public: true

